version: '2'
services:
  mqtt:
    build: ./mqtt
    expose:
      - "1883"
    privileged: true
    network_mode: "host"
  flogo:
    build: ./flogo
    expose:
      - "80"
    pid: "host"
    network_mode: "host"
    privileged: true