version: '2'
services:
  cserver:
    build: ./mqtt
    expose:
      - "1883:1883"
      - "9001:9001"
    volumes:
            - "${PWD}/data:/mqtt/data"
            - "${PWD}/logs:/mqtt/logs"
    pid: "host"
    network_mode: "host"
    privileged: true